# encoding: utf-8

from django.utils.translation import ugettext as _
from django.db import models
from django.conf import settings

try:
    from south.modelsinspector import add_introspection_rules
    _using_south = 'south' in settings.INSTALLED_APPS
except ImportError:
    # Don't complain if South is not available
    _using_south = False
# If not using South we won't need this
if not _using_south:
    del add_introspection_rules

# Codes for the Representation of Names of Languages
# (Ref.: http://www.loc.gov/standards/iso639-2/php/code_list.php
#        via http://www.i18nguy.com/unicode/language-identifiers.html)
LANGUAGES = (
    ('aa', _('Afar')),
    ('ab', _('Abkhazian')),
    ('af', _('Afrikaans')),
    ('ak', _('Akan')),
    ('sq', _('Albanian')),
    ('am', _('Amharic')),
    ('ar', _('Arabic')),
    ('an', _('Aragonese')),
    ('hy', _('Armenian')),
    ('as', _('Assamese')),
    ('av', _('Avaric')),
    ('ae', _('Avestan')),
    ('ay', _('Aymara')),
    ('az', _('Azerbaijani')),
    ('ba', _('Bashkir')),
    ('bm', _('Bambara')),
    ('eu', _('Basque')),
    ('be', _('Belarusian')),
    ('bn', _('Bengali')),
    ('bh', _('Bihari languages')),
    ('bi', _('Bislama')),
    ('bo', _('Tibetan')),
    ('bs', _('Bosnian')),
    ('br', _('Breton')),
    ('bg', _('Bulgarian')),
    ('my', _('Burmese')),
    ('ca', _('Catalan; Valencian')),
    ('cs', _('Czech')),
    ('ch', _('Chamorro')),
    ('ce', _('Chechen')),
    ('zh', _('Chinese')),
    ('cu', _('Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic')),
    ('cv', _('Chuvash')),
    ('kw', _('Cornish')),
    ('co', _('Corsican')),
    ('cr', _('Cree')),
    ('cy', _('Welsh')),
    ('cs', _('Czech')),
    ('da', _('Danish')),
    ('de', _('German')),
    ('dv', _('Divehi; Dhivehi; Maldivian')),
    ('nl', _('Dutch; Flemish')),
    ('dz', _('Dzongkha')),
    ('el', _('Greek, Modern (1453-)')),
    ('en', _('English')),
    ('eo', _('Esperanto')),
    ('et', _('Estonian')),
    ('eu', _('Basque')),
    ('ee', _('Ewe')),
    ('fo', _('Faroese')),
    ('fa', _('Persian')),
    ('fj', _('Fijian')),
    ('fi', _('Finnish')),
    ('fr', _('French')),
    ('fr', _('French')),
    ('fy', _('Western Frisian')),
    ('ff', _('Fulah')),
    ('ka', _('Georgian')),
    ('de', _('German')),
    ('gd', _('Gaelic; Scottish Gaelic')),
    ('ga', _('Irish')),
    ('gl', _('Galician')),
    ('gv', _('Manx')),
    ('el', _('Greek, Modern (1453-)')),
    ('gn', _('Guarani')),
    ('gu', _('Gujarati')),
    ('ht', _('Haitian; Haitian Creole')),
    ('ha', _('Hausa')),
    ('he', _('Hebrew')),
    ('hz', _('Herero')),
    ('hi', _('Hindi')),
    ('ho', _('Hiri Motu')),
    ('hr', _('Croatian')),
    ('hu', _('Hungarian')),
    ('hy', _('Armenian')),
    ('ig', _('Igbo')),
    ('is', _('Icelandic')),
    ('io', _('Ido')),
    ('ii', _('Sichuan Yi; Nuosu')),
    ('iu', _('Inuktitut')),
    ('ie', _('Interlingue; Occidental')),
    ('ia', _('Interlingua (International Auxiliary Language Association)')),
    ('id', _('Indonesian')),
    ('ik', _('Inupiaq')),
    ('is', _('Icelandic')),
    ('it', _('Italian')),
    ('jv', _('Javanese')),
    ('ja', _('Japanese')),
    ('kl', _('Kalaallisut; Greenlandic')),
    ('kn', _('Kannada')),
    ('ks', _('Kashmiri')),
    ('ka', _('Georgian')),
    ('kr', _('Kanuri')),
    ('kk', _('Kazakh')),
    ('km', _('Central Khmer')),
    ('ki', _('Kikuyu; Gikuyu')),
    ('rw', _('Kinyarwanda')),
    ('ky', _('Kirghiz; Kyrgyz')),
    ('kv', _('Komi')),
    ('kg', _('Kongo')),
    ('ko', _('Korean')),
    ('kj', _('Kuanyama; Kwanyama')),
    ('ku', _('Kurdish')),
    ('lo', _('Lao')),
    ('la', _('Latin')),
    ('lv', _('Latvian')),
    ('li', _('Limburgan; Limburger; Limburgish')),
    ('ln', _('Lingala')),
    ('lt', _('Lithuanian')),
    ('lb', _('Luxembourgish; Letzeburgesch')),
    ('lu', _('Luba-Katanga')),
    ('lg', _('Ganda')),
    ('mk', _('Macedonian')),
    ('mh', _('Marshallese')),
    ('ml', _('Malayalam')),
    ('mi', _('Maori')),
    ('mr', _('Marathi')),
    ('ms', _('Malay')),
    ('mk', _('Macedonian')),
    ('mg', _('Malagasy')),
    ('mt', _('Maltese')),
    ('mn', _('Mongolian')),
    ('mi', _('Maori')),
    ('ms', _('Malay')),
    ('my', _('Burmese')),
    ('na', _('Nauru')),
    ('nv', _('Navajo; Navaho')),
    ('nr', _('Ndebele, South; South Ndebele')),
    ('nd', _('Ndebele, North; North Ndebele')),
    ('ng', _('Ndonga')),
    ('ne', _('Nepali')),
    ('nl', _('Dutch; Flemish')),
    ('nn', _('Norwegian Nynorsk; Nynorsk, Norwegian')),
    ('nb', _('Bokmål, Norwegian; Norwegian Bokmål')),
    ('no', _('Norwegian')),
    ('ny', _('Chichewa; Chewa; Nyanja')),
    ('oc', _('Occitan (post 1500)')),
    ('oj', _('Ojibwa')),
    ('or', _('Oriya')),
    ('om', _('Oromo')),
    ('os', _('Ossetian; Ossetic')),
    ('pa', _('Panjabi; Punjabi')),
    ('fa', _('Persian')),
    ('pi', _('Pali')),
    ('pl', _('Polish')),
    ('pt', _('Portuguese')),
    ('ps', _('Pushto; Pashto')),
    ('qu', _('Quechua')),
    ('rm', _('Romansh')),
    ('ro', _('Romanian; Moldavian; Moldovan')),
    ('ro', _('Romanian; Moldavian; Moldovan')),
    ('rn', _('Rundi')),
    ('ru', _('Russian')),
    ('sg', _('Sango')),
    ('sa', _('Sanskrit')),
    ('si', _('Sinhala; Sinhalese')),
    ('sk', _('Slovak')),
    ('sk', _('Slovak')),
    ('sl', _('Slovenian')),
    ('se', _('Northern Sami')),
    ('sm', _('Samoan')),
    ('sn', _('Shona')),
    ('sd', _('Sindhi')),
    ('so', _('Somali')),
    ('st', _('Sotho, Southern')),
    ('es', _('Spanish; Castilian')),
    ('sq', _('Albanian')),
    ('sc', _('Sardinian')),
    ('sr', _('Serbian')),
    ('ss', _('Swati')),
    ('su', _('Sundanese')),
    ('sw', _('Swahili')),
    ('sv', _('Swedish')),
    ('ty', _('Tahitian')),
    ('ta', _('Tamil')),
    ('tt', _('Tatar')),
    ('te', _('Telugu')),
    ('tg', _('Tajik')),
    ('tl', _('Tagalog')),
    ('th', _('Thai')),
    ('bo', _('Tibetan')),
    ('ti', _('Tigrinya')),
    ('to', _('Tonga (Tonga Islands)')),
    ('tn', _('Tswana')),
    ('ts', _('Tsonga')),
    ('tk', _('Turkmen')),
    ('tr', _('Turkish')),
    ('tw', _('Twi')),
    ('ug', _('Uighur; Uyghur')),
    ('uk', _('Ukrainian')),
    ('ur', _('Urdu')),
    ('uz', _('Uzbek')),
    ('ve', _('Venda')),
    ('vi', _('Vietnamese')),
    ('vo', _('Volapük')),
    ('cy', _('Welsh')),
    ('wa', _('Walloon')),
    ('wo', _('Wolof')),
    ('xh', _('Xhosa')),
    ('yi', _('Yiddish')),
    ('yo', _('Yoruba')),
    ('za', _('Zhuang; Chuang')),
    ('zh', _('Chinese')),
    ('zu', _('Zulu')),
)

# English country names and code elements
# (Ref.: http://www.iso.org/iso/country_codes/iso_3166_code_lists/english_country_names_and_code_elements.htm
#        via http://www.i18nguy.com/unicode/language-identifiers.html)
COUNTRIES = (
    ('af', _('Afghanistan')),
    ('ax', _('Åland Islands')),
    ('al', _('Albania')),
    ('dz', _('Algeria')),
    ('as', _('American Samoa')),
    ('ad', _('Andorra')),
    ('ao', _('Angola')),
    ('ai', _('Anguilla')),
    ('aq', _('Antarctica')),
    ('ag', _('Antigua and Barbuda')),
    ('ar', _('Argentina')),
    ('am', _('Armenia')),
    ('aw', _('Aruba')),
    ('au', _('Australia')),
    ('at', _('Austria')),
    ('az', _('Azerbaijan')),
    ('bs', _('Bahamas')),
    ('bh', _('Bahrain')),
    ('bd', _('Bangladesh')),
    ('bb', _('Barbados')),
    ('by', _('Belarus')),
    ('be', _('Belgium')),
    ('bz', _('Belize')),
    ('bj', _('Benin')),
    ('bm', _('Bermuda')),
    ('bt', _('Bhutan')),
    ('bo', _('Bolivia, Plurinational State of')),
    ('ba', _('Bosnia and Herzegovina')),
    ('bw', _('Botswana')),
    ('bv', _('Bouvet Island')),
    ('br', _('Brazil')),
    ('io', _('British Indian Ocean Territory')),
    ('bn', _('Brunei Darussalam')),
    ('bg', _('Bulgaria')),
    ('bf', _('Burkina Faso')),
    ('bi', _('Burundi')),
    ('kh', _('Cambodia')),
    ('cm', _('Cameroon')),
    ('ca', _('Canada')),
    ('cv', _('Cape Verde')),
    ('ky', _('Cayman Islands')),
    ('cf', _('Central African Republic')),
    ('td', _('Chad')),
    ('cl', _('Chile')),
    ('cn', _('China')),
    ('cx', _('Christmas Island')),
    ('cc', _('Cocos (Keeling) Islands')),
    ('co', _('Colombia')),
    ('km', _('Comoros')),
    ('cg', _('Congo')),
    ('cd', _('Congo, The Democratic Republic of The')),
    ('ck', _('Cook Islands')),
    ('cr', _('Costa Rica')),
    ('ci', _('Côte D\'Ivoire')),
    ('hr', _('Croatia')),
    ('cu', _('Cuba')),
    ('cy', _('Cyprus')),
    ('cz', _('Czech Republic')),
    ('dk', _('Denmark')),
    ('dj', _('Djibouti')),
    ('dm', _('Dominica')),
    ('do', _('Dominican Republic')),
    ('ec', _('Ecuador')),
    ('eg', _('Egypt')),
    ('sv', _('El Salvador')),
    ('gq', _('Equatorial Guinea')),
    ('er', _('Eritrea')),
    ('ee', _('Estonia')),
    ('et', _('Ethiopia')),
    ('fk', _('Falkland Islands (Malvinas)')),
    ('fo', _('Faroe Islands')),
    ('fj', _('Fiji')),
    ('fi', _('Finland')),
    ('fr', _('France')),
    ('gf', _('French Guiana')),
    ('pf', _('French Polynesia')),
    ('tf', _('French Southern Territories')),
    ('ga', _('Gabon')),
    ('gm', _('Gambia')),
    ('ge', _('Georgia')),
    ('de', _('Germany')),
    ('gh', _('Ghana')),
    ('gi', _('Gibraltar')),
    ('gr', _('Greece')),
    ('gl', _('Greenland')),
    ('gd', _('Grenada')),
    ('gp', _('Guadeloupe')),
    ('gu', _('Guam')),
    ('gt', _('Guatemala')),
    ('gg', _('Guernsey')),
    ('gn', _('Guinea')),
    ('gw', _('Guinea-Bissau')),
    ('gy', _('Guyana')),
    ('ht', _('Haiti')),
    ('hm', _('Heard Island and Mcdonald Islands')),
    ('va', _('Holy See (Vatican City State)')),
    ('hn', _('Honduras')),
    ('hk', _('Hong Kong')),
    ('hu', _('Hungary')),
    ('is', _('Iceland')),
    ('in', _('India')),
    ('id', _('Indonesia')),
    ('ir', _('Iran, Islamic Republic of')),
    ('iq', _('Iraq')),
    ('ie', _('Ireland')),
    ('im', _('Isle of Man')),
    ('il', _('Israel')),
    ('it', _('Italy')),
    ('jm', _('Jamaica')),
    ('jp', _('Japan')),
    ('je', _('Jersey')),
    ('jo', _('Jordan')),
    ('kz', _('Kazakhstan')),
    ('ke', _('Kenya')),
    ('ki', _('Kiribati')),
    ('kp', _('Korea, Democratic People\'s Republic of')),
    ('kr', _('Korea, Republic of')),
    ('kw', _('Kuwait')),
    ('kg', _('Kyrgyzstan')),
    ('la', _('Lao People\'s Democratic Republic')),
    ('lv', _('Latvia')),
    ('lb', _('Lebanon')),
    ('ls', _('Lesotho')),
    ('lr', _('Liberia')),
    ('ly', _('Libyan Arab Jamahiriya')),
    ('li', _('Liechtenstein')),
    ('lt', _('Lithuania')),
    ('lu', _('Luxembourg')),
    ('mo', _('Macao')),
    ('mk', _('Macedonia, The Former Yugoslav Republic of')),
    ('mg', _('Madagascar')),
    ('mw', _('Malawi')),
    ('my', _('Malaysia')),
    ('mv', _('Maldives')),
    ('ml', _('Mali')),
    ('mt', _('Malta')),
    ('mh', _('Marshall Islands')),
    ('mq', _('Martinique')),
    ('mr', _('Mauritania')),
    ('mu', _('Mauritius')),
    ('yt', _('Mayotte')),
    ('mx', _('Mexico')),
    ('fm', _('Micronesia, Federated States of')),
    ('md', _('Moldova, Republic of')),
    ('mc', _('Monaco')),
    ('mn', _('Mongolia')),
    ('me', _('Montenegro')),
    ('ms', _('Montserrat')),
    ('ma', _('Morocco')),
    ('mz', _('Mozambique')),
    ('mm', _('Myanmar')),
    ('na', _('Namibia')),
    ('nr', _('Nauru')),
    ('np', _('Nepal')),
    ('nl', _('Netherlands')),
    ('an', _('Netherlands Antilles')),
    ('nc', _('New Caledonia')),
    ('nz', _('New Zealand')),
    ('ni', _('Nicaragua')),
    ('ne', _('Niger')),
    ('ng', _('Nigeria')),
    ('nu', _('Niue')),
    ('nf', _('Norfolk Island')),
    ('mp', _('Northern Mariana Islands')),
    ('no', _('Norway')),
    ('om', _('Oman')),
    ('pk', _('Pakistan')),
    ('pw', _('Palau')),
    ('ps', _('Palestinian Territory, Occupied')),
    ('pa', _('Panama')),
    ('pg', _('Papua New Guinea')),
    ('py', _('Paraguay')),
    ('pe', _('Peru')),
    ('ph', _('Philippines')),
    ('pn', _('Pitcairn')),
    ('pl', _('Poland')),
    ('pt', _('Portugal')),
    ('pr', _('Puerto Rico')),
    ('qa', _('Qatar')),
    ('re', _('Réunion')),
    ('ro', _('Romania')),
    ('ru', _('Russian Federation')),
    ('rw', _('Rwanda')),
    ('bl', _('Saint Barthélemy')),
    ('sh', _('Saint Helena, Ascension and Tristan Da Cunha')),
    ('kn', _('Saint Kitts and Nevis')),
    ('lc', _('Saint Lucia')),
    ('mf', _('Saint Martin')),
    ('pm', _('Saint Pierre and Miquelon')),
    ('vc', _('Saint Vincent and The Grenadines')),
    ('ws', _('Samoa')),
    ('sm', _('San Marino')),
    ('st', _('Sao Tome and Principe')),
    ('sa', _('Saudi Arabia')),
    ('sn', _('Senegal')),
    ('rs', _('Serbia')),
    ('sc', _('Seychelles')),
    ('sl', _('Sierra Leone')),
    ('sg', _('Singapore')),
    ('sk', _('Slovakia')),
    ('si', _('Slovenia')),
    ('sb', _('Solomon Islands')),
    ('so', _('Somalia')),
    ('za', _('South Africa')),
    ('gs', _('South Georgia and The South Sandwich Islands')),
    ('es', _('Spain')),
    ('lk', _('Sri Lanka')),
    ('sd', _('Sudan')),
    ('sr', _('Suriname')),
    ('sj', _('Svalbard and Jan Mayen')),
    ('sz', _('Swaziland')),
    ('se', _('Sweden')),
    ('ch', _('Switzerland')),
    ('sy', _('Syrian Arab Republic')),
    ('tw', _('Taiwan, Province of China')),
    ('tj', _('Tajikistan')),
    ('tz', _('Tanzania, United Republic of')),
    ('th', _('Thailand')),
    ('tl', _('Timor-Leste')),
    ('tg', _('Togo')),
    ('tk', _('Tokelau')),
    ('to', _('Tonga')),
    ('tt', _('Trinidad and Tobago')),
    ('tn', _('Tunisia')),
    ('tr', _('Turkey')),
    ('tm', _('Turkmenistan')),
    ('tc', _('Turks and Caicos Islands')),
    ('tv', _('Tuvalu')),
    ('ug', _('Uganda')),
    ('ua', _('Ukraine')),
    ('ae', _('United Arab Emirates')),
    ('gb', _('United Kingdom')),
    ('us', _('United States')),
    ('um', _('United States Minor Outlying Islands')),
    ('uy', _('Uruguay')),
    ('uz', _('Uzbekistan')),
    ('vu', _('Vanuatu')),
    ('ve', _('Venezuela, Bolivarian Republic of')),
    ('vn', _('Viet Nam')),
    ('vg', _('Virgin Islands, British')),
    ('vi', _('Virgin Islands, U.S.')),
    ('wf', _('Wallis And Futuna')),
    ('eh', _('Western Sahara')),
    ('ye', _('Yemen')),
    ('zm', _('Zambia')),
    ('zw', _('Zimbabwe')),
)

class LanguageField(models.CharField):
    """Stores language codes as defined by ISO 639-1"""

    description = _("Stores language codes")

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('max_length', 2)
        kwargs.setdefault('choices', LANGUAGES)

        super(LanguageField, self).__init__(*args, **kwargs)

    def get_internal_type(self):
        return 'CharField'

if _using_south:
    add_introspection_rules([], ["^trango_missing\.fields\.LanguageField"])


class CountryField(models.CharField):
    """Stores language codes as defined by ISO 3166-1-alpha-2"""

    description = _("Stores country codes")

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('max_length', 2)
        kwargs.setdefault('choices', COUNTRIES)

        super(CountryField, self).__init__(*args, **kwargs)

    def get_internal_type(self):
        return 'CharField'

if _using_south:
    add_introspection_rules([], ["^trango_missing\.fields\.CountryField"])

# End of file
